### ISSUE TITLE
Move documentation to single-spa.js.org?

### ISSUE THREAD

**Issue by internettrans** [emtecinc/single-spa-backbone#2]
Hi there @emtecinc,

Thanks for creating and maintaining this project. I'd like the entire single spa community to be aware of this project, use it, and contribute to it. Would you be interested in your project being linked to from single-spa.js.org? Also, we've recently been making an effort to move all documentation from individual readmes into single-spa.js.org. Would you be interested in that happening for single-spa-backbone?

If so, I'm happy to make PRs to move the docs over.

**Comment by debashish2014** [comment]
Hi @joeldenning, 

Thank you so much. It will be really great if this project gets linked to single-spa.js.org.
Please feel free to make PR.
