### ISSUE TITLE
npm and github permissions

### ISSUE THREAD

**Issue by internettrans** [emtecinc/single-spa-backbone#5]
Hi there,

Could you give me access on Github and npm so that I can help maintain this project?

For npm you just run this in the console:
```sh
npm owner add joeldenning @emtecinc/single-spa-backbone
```

**Comment by debashish2014** [comment]
Hi @joeldenning, I have given you access to Github repository. However, I am getting team not found error while adding you as an npm owner.

![image](https://user-images.githubusercontent.com/8132553/62106959-312ede00-b2c4-11e9-9eaa-02de89035008.png)

**Comment by internettrans** [comment]
Looks like `@emtcinc` is an npm org, not an npm user? I would need to be added to that org first before you could add me as an owner in the terminal. See related https://github.com/jstransformers/jstransformer-riotjs/issues/22 which explains how to do this.

**Comment by debashish2014** [comment]
Permission granted
