### ISSUE TITLE
Webpack integration

### ISSUE THREAD

**Issue by jualoppaz** [emtecinc/single-spa-backbone#6]
Hi!

I'm trying to apply **single-spa** to an existing **Backbone** app and, after that, define another **single-spa** app with another technology.

My existing app has whole **Backbone** project compiled with **Webpack** and I'm trying to configure the singleSpaBackbone strategy with Production build configuration like this:

```
import singleSpaBackbone from '@emtecinc/single-spa-backbone';

const backBoneLifecycles = singleSpaBackbone({
	BasePath: './',
	App:
	{
            AppPath: 'src/backbone'
	},
	DomElementSetter: domElementSetter
});

export const bootstrap = [
	backBoneLifecycles.bootstrap,
];

export const mount = [
	backBoneLifecycles.mount,
];

export const unmount = [
	backBoneLifecycles.unmount
];


function domElementSetter() {
	//use the same element to render into in the backbone app
	let el = document.getElementById('app-placeholder');
	if (!el) {
		el = window.document.createElement('div');
		el.id = 'app-placeholder';
		document.body.appendChild(el);
	}
}
```

This file is in a **src/backbone** folder in my project.

When I launch my app I can see a script HTML tag like:

```
<script src="/src/backbone"></script>
```

This has no sense because is a project folder, and I only serve the build folder generated by **Webpack**.

Besides that, I want to know if is possible to not include any script tag with **singleSpaBackbone** and let **Webpack** to include the required tags by itself.

Thank you sou much.

**Comment by internettrans** [comment]
Hi @jualoppaz, one thing you'll need to do when migrating from single-spa is free the html file from webpack. The reason is that each single-spa application has its own webpack config, but there is only one html file that all of them share. See related https://single-spa.js.org/docs/configuration and http://single-spa-playground.org/playground/html-file.

Another thing to think about is how to implement the [single-spa activity functions](https://single-spa.js.org/docs/configuration#activity-function). For this, I recommend using [the recommended setup](https://single-spa.js.org/docs/faq/#is-there-a-recommended-setup) which includes SystemJS. Once you do that, the code you've pasted above should work great!

**Comment by jualoppaz** [comment]
Hi @joeldenning !

In my case I was injecting several scripts twice due to initial Webpack config. After reading your comment, I only had to disable automatic Webpack scripts import with HtmlWebpackPlugin and import the needed scripts manually.

An example of this portion of code would be the next:

```
...,
plugins: [
    new HtmlWebpackPlugin({
      title: 'App title',
      baseUri: '/',
      template: path.resolve(__dirname, 'src/index.html'),
      inject: false
    }),
  ],
...
```

Thank you so much for your help!

**Comment by internettrans** [comment]
Glad to hear that you got things working.

**Comment by jualoppaz** [comment]
Hi again @joeldenning !

Although my app is working using standard imports for config the **singleSpaEntry** file for each **registered application**, I am researching about **SystemJS.import** in order to split my application and upgrade my **monolithic** strategy (option 1) to **NPM packages** strategy (option 2) and why not adopt in the future the **dynamic module** strategy (option 3).

In order to starting the upgrade to Option number 2 I'm doing experiments with the repo https://gitlab.com/TheMcMurder/single-spa-portal-example but I have several doubts.

- Is it possible to use **SystemJS** for load **NPM packages** as same time loading application files?

- If I set the **libraryTarget** webpack option to **amd** my **Backbone** app is not fired although the script tag is correctly added by **single-spa**. I tried to use **system** value after upgrading my **webpack** version to **4.30.0** but I have the same problem. Do I have to perform any special configuration to get firing my **backbone** main bundled file like **IIFE**?

Thank you so much.

**Comment by internettrans** [comment]
> Is it possible to use SystemJS for load NPM packages as same time loading application files?

Are you asking if you can have shared npm dependencies for your packages? Yes, you can! See https://single-spa.js.org/docs/faq/#can-i-have-only-one-version-of-react-vue-angular-etc-loaded

> If I set the libraryTarget webpack option to amd my Backbone app is not fired although the script tag is correctly added by single-spa. I tried to use system value after upgrading my webpack version to 4.30.0 but I have the same problem. Do I have to perform any special configuration to get firing my backbone main bundled file like IIFE?

If you're using SystemJS, I'd recommend setting `output.libraryTarget` to `'system'`. See https://webpack.js.org/configuration/output/#module-definition-systems. Doing so might help

**Comment by jualoppaz** [comment]
I think the problem is in my entry property in my webpack config.

My current configuration is the next

**webpack.config.js**
```javascript
module.exports = {
    ...,
    entry {
        main: ['babel-polyfill', './single-spa-applications.js'],
        'backbone-app': ['./backbone/index.js'],
        'backbone-sspa': ['./backbone/singleSpaEntry.js']
    }
}
```

The **main.bundle.js** would be the **root-application**, the **backbone.app.bundle** will be my **Backbone** app and the **backbone-sspa.bundle.js** will have only the **singleSpaBackbone** configuration.

**index.html**
```html
...
<body>
        <script type="systemjs-importmap">
          {
            "imports": {
              "@app/main": "./main.bundle.js",
              "@app/backbone-app": "./backbone-sspa.bundle.js",
              "@app/vue-app": "../node_modules/vue-app/dist/js/app"
            }
          }
        </script>
        <script src='https://unpkg.com/systemjs@4.1.0/dist/system.js'></script>
        <script src='https://unpkg.com/systemjs@4.1.0/dist/extras/amd.js'></script>
        <script src='https://unpkg.com/systemjs@4.1.0/dist/extras/named-exports.js'></script>
        <script src='https://unpkg.com/systemjs@4.1.0/dist/extras/use-default.js'></script>
        <script>
          System.import("@app/main")
        </script>
        <div id="app-placeholder"></div>
    </body>
```

**single-spa-applications.js**
```javascript
singleSpa.registerApplication('backbone', () => System.import('@app/backbone-app'), () => true);
singleSpa.registerApplication('vue', () => System.import('@app/vue-app'), showWhen(['/vue-route']));
```

**singleSpaEntry.js**
```javascript

import singleSpaBackbone from '@emtecinc/single-spa-backbone';

const backBoneLifecycles = singleSpaBackbone({
	BasePath: './',
	App:
	{
    AppPath: 'backbone-app.bundle.js',
	},
	DomElementSetter: domElementSetter
});

export const bootstrap = [
  backBoneLifecycles.bootstrap,
];

export const mount = [
  backBoneLifecycles.mount,
];

export const unmount = [
  backBoneLifecycles.unmount,
];


function domElementSetter() {
    //use the same element to render into in the backbone app
    let el = document.getElementById('app-placeholder');
    if (!el) {
	el = window.document.createElement('div');
	el.id = 'app-placeholder';
	document.body.appendChild(el);
    }
}
```

I think that **SystemJS** can't relate **backbone-app.bundle.js** from **backbone-sspa.bundle.js**. If I merge that files removing the last entry, I can see my app working with **SystemJS**.

Now the files would be like follows:

**webpack.config.js**
```javascript
module.exports = {
    ...,
    entry {
        main: ['babel-polyfill', './single-spa-applications.js'],
        'backbone-app': ['./backbone/index.js']
    }
}
```

**index.html**
```html
...
<body>
        <script type="systemjs-importmap">
          {
            "imports": {
              "@app/main": "./main.bundle.js",
              "@app/backbone-app": "./backbone-app.bundle.js",
              "@app/vue-app": "../node_modules/vue-app/dist/js/app"
            }
          }
        </script>
        <script src='https://unpkg.com/systemjs@4.1.0/dist/system.js'></script>
        <script src='https://unpkg.com/systemjs@4.1.0/dist/extras/amd.js'></script>
        <script src='https://unpkg.com/systemjs@4.1.0/dist/extras/named-exports.js'></script>
        <script src='https://unpkg.com/systemjs@4.1.0/dist/extras/use-default.js'></script>
        <script>
          System.import("@app/main")
        </script>
        <div id="app-placeholder"></div>
    </body>
```

However, it seems that **singleSpaBackbone** is fired twice and the second attempt is not valid. This is the produced error:

![error navegador pero arranca](https://user-images.githubusercontent.com/5088244/70250203-d2033d80-177d-11ea-8044-79a7244feace.PNG)

![error bootstrap, mount y unmount](https://user-images.githubusercontent.com/5088244/70249141-43da8780-177c-11ea-9edb-3dc1c68e8b23.PNG)

It's normal that this error occurs because I am using twice the backbone-app.bundle.js file in the **process**: as **singleSpaBackbone appPath** and as **loadingFunctions** parameter of **registerApplication singleSpa** method.

The reason for have two entries is that I am **mixing** the **root-application** repo with the **backbone-repo** by the moment.

- Is problematic that I have more than one entry?
- Can I say to SystemJS how to relate the generated bundles?

Thank you so much.

**Comment by internettrans** [comment]
Yeah I'd recommend switching to only one webpack entrypoint. You can use `import()` to do code splits.

**Comment by jualoppaz** [comment]
Ok @joeldenning . I changed again my **System.import** calls by **import** by the moment and it's working.

I'll try to use System.import when I could split my apps with only one entry per repository.

Thank you so much!!
